#!/bin/bash
#skip uninstallation if executed from an update
if [[ "$1" != "update" ]];then
  cd ~/Cracked-MultiMC && find ./install -mindepth 1 ! -regex '^./install/instances\(/.*\)?' -delete
  sudo rm -rf ~/Cracked-MultiMC/src
  sudo rm -rf ~/Cracked-MultiMC/build
  sudo rm -rf ~/.local/share/applications/Cracked-MultiMC.desktop
  sudo rm -rf ~/.local/share/icons/Cracked-MultiMC/icon-64.png

  purge_packages || error "Dependencies failed to uninstall"

  remove_repofile_if_unused /etc/apt/sources.list.d/adoptium.list
  remove_repofile_if_unused /etc/apt/sources.list.d/adoptopenjdk.list
else
  echo "Uninstall skipped because run from the updater"
fi
